# un paquet simple, pas relié à un dépôt ou quoi que ce soit. Juste le nom d'un paquet et sa version actuelle
Hal\ReleaseBundle\Entity\Package:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: auto }
  fields:
    name:
      type: string
    currentVersion:
      type: version
      nullable: true
    releaseDate:
      type: datetime
      nullable: true
    url:
      type: string
      nullable: true
  oneToMany:
      requiredBy:
        targetEntity: Requirement
        mappedBy: Package
