hal_entity_overriding:
    resource: "@HalEntityOverridingBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hal_release_web:
    resource: "@HalReleaseWebBundle/Resources/config/routing.yml"
    prefix:   /

hal_github:
    resource: "@HalGithubBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
