parameters:
  hal.releaseweb.twig.extension.requirement_status.class: Hal\ReleaseWebBundle\Twig\Extension\RequirementStateExtension

services:
  hal.releaseweb.twig.extension.requirement_status:
      class: %hal.releaseweb.twig.extension.requirement_status.class%
      tags:
        - {name: twig.extension}
      arguments:
        - @hal.release.requirement.service
