parameters:
#    hal_release_web.example.class: Hal\ReleaseWebBundle\Example

services:
#    hal_release_web.example:
#        class: %hal_release_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
