Hal\Bundle\GithubBundle\Entity\Branche:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: auto }
  fields:
    name:
      type: string
    lastUpdate:
          type: datetime
  manyToOne:
    repository:
      targetEntity: Repository
      cascade: ["persist", "merge","remove"]
  lifecycleCallbacks:
    prePersist: [ updateDate ]
    preUpdate:  [ updateDate ]

